# Ansible playbook AWS - install docker
---
- name: "AWS - Install docker"
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker
      shell: "sudo yum install docker -y"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log into DockerHub
      shell: "sudo docker login -u sukumarvommina1 -p Pandu@089"
      
    - name: pull an image
      shell: "sudo docker pull sukumarvommina1/casestudy-springboot1:1.0"
      
    - name: execute image
      shell: "sudo docker run -p 80:8585 -d sukumarvommina1/casestudy-springboot1:1.0"
