- name: ec2-launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launch ec2
    ec2:
      instance_type: t2.micro
      key_name: devops-key
      image: ami-097834fcb3081f51a
      region: us-east-2
      group: launch-wizard-1
      count: 1
      vpc_subnet_id: subnet-f5cbcc8f
      wait: yes
      assign_public_ip: yes
    register: ec2_casestudy
