# Ansible playbook AWS - install docker
---
- name: "AWS - Install docker"
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=18.06.1 -y"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log into DockerHub
      docker_login:
        username: sukumarvommina1
        password: Pandu@089

    - name: pull an image
       docker_image:
        name: sukumarvommina1/casestudy-springboot1:1.0
        source: pull
    
    - name: execute image
      shell: "sudo docker run -p 80:8585 -d sukumarvommina1/casestudy-springboot1:1.0"
