- name: ec2-launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launch ec2
    ec2:
      instance_type: t2.micro
      key_name: devops-key
      image: ami-097834fcb3081f51a
      region: us-east-2
      group: launch-wizard-1
      count: 1
      vpc_subnet_id: subnet-f5cbcc8f
      wait: yes
      assign_public_ip: yes
    register: ec2_casestudy
    
  - name: Add the newly created EC2 instance(s) to the local host group
    local_action: lineinfile 
             path=local-hots.txt
             regexp={{ item.public_ip }} 
            insertafter='\[casestudy\]' line={{ item.public_ip }}
    with_items: '{{ec2_casestudy.instances}}'
 
  - name: Add new instance to Casestudy's host group
    add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
    with_items: "{{ ec2_casestudy.instances }}"
